version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    #container_name: kitty_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    #container_name: kitty_backend
    image: bogdartem/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    #container_name: kitty_frontend
    env_file: .env
    image: bogdartem/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    #container_name: kitty_gateway
    image: bogdartem/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/app/media
    depends_on:
      - backend
      - frontend
